export const constants = {
    CON_INVERSTORGAIN_URL : 'https://www.investorgain.com/gmp/ipo-gmp/',
    CON_BSE_MAIN_URL:'https://www.bseindia.com/markets/publicIssues/CummDemandSchedule.aspx?ID=',
    //CON_BSE_SME_URL:'https://www.bseindia.com/markets/publicIssues/BSEDemandSchedule_new.aspx?Scripcode=',
    CON_BSE_SME_URL:'https://www.bseindia.com/markets/publicIssues/BSEDemandSchedule_FPO.aspx?Scripcode=',
    CON_CHITTOR_URL: 'https://www.chittorgarh.com/ipo/',
    CON_DATE_YYMMDDHHMMSS: 'YYYY-MM-DD HH:mm:ss',
    CON_DATE_YYMMDD: 'YYYY-MM-DD',
    CON_DATE_DDMMYY: 'DD-MM-YYYY',
    CON_QIB: 'QIB',
    CON_NII: 'NII',
    CON_NIB: 'NIB',
    CON_RETAIL: 'RETAIL',
    CON_QIBs: 'QIBS',
    CON_EMPLOYEES: 'EMPLOYEES',
    CON_HNIs: 'HNIS',
    CON_HNIs10L: 'HNIS (10L+)',
    CON_HNIs10LOLD: 'HNIS (10+L)',
    CON_HNIs2TO10L: 'HNIS (2-10L)',
    CON_SHAREHOLDERS: 'SHAREHOLDERS',
    CON_QUALIFIED_INSTITUTIONS: 'QUALIFIED INSTITUTIONS',
    CON_NON_INSTITUTIONAL_BUYERS: 'NON-INSTITUTIONAL BUYERS',
    CON_NON_INSTITUTIONAL_BUYERS_3STAR: 'NON-INSTITUTIONAL BUYERS***',
    CON_BNII_ABOVE_10L: 'BNII (BIDS ABOVE ₹10L)',
    CON_SNII_BELOW_10L: 'SNII (BIDS BELOW ₹10L)',
    CON_RETAIL_INVESTORS: 'RETAIL INVESTORS',
    CON_OTHERS: 'OTHERS',
    CON_UPDATED_ON: 'UPDATED ON',
    CON_QUALIFIED_INSTITUTIONAL_BUYERS: 'QUALIFIED INSTITUTIONAL BUYERS',
    CON_NON_INSTITUTIONAL_INVESTORS: 'NON INSTITUTIONAL INVESTORS',
    CON_RETAIL_INDIVIDUAL_INVESTORS: 'RETAIL INDIVIDUAL INVESTORS',
    CON_SHAREHOLDER: 'SHAREHOLDER',
    CON_EMPLOYEE_RESERVED: 'EMPLOYEE RESERVED',
    CON_UPDATED_AS_ON: 'UPDATED AS ON',

    CON_QIB_50: 'Not more than 50.00% of the Net offer',
    CON_QIB_75: '75.00% of the Net offer',
    CON_HNI_15: 'Not less than 15.00% of the Offer',
    CON_RETAIL_35: 'Not less than 35.00% of the Offer',
    CON_RETAIL_10: 'Not more than 10.00% of the Offer',
    CON_RETAIL_50: '50.00% of the Offer',
    CON_HNI_50: '50.00% of the Offer',

}